import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:latlong2/latlong.dart';

import 'package:sakay_ta_mobile_app/core/constants.dart';
import 'package:sakay_ta_mobile_app/models/favorite_location.dart';
import 'package:sakay_ta_mobile_app/models/route_result.dart';
import 'package:sakay_ta_mobile_app/providers/route_state_provider.dart';
import 'package:sakay_ta_mobile_app/providers/map_state_provider.dart';
import 'package:sakay_ta_mobile_app/services/geocoding_service.dart';
import 'package:sakay_ta_mobile_app/services/hive_service.dart';
import 'package:sakay_ta_mobile_app/services/osrm_service.dart';

class MainBottomSheet extends StatelessWidget {
  final DraggableScrollableController sheetController;
  final int selectedIndex;
  final bool hasSuggestedRoutes;

  final VoidCallback onDrawMapElements;
  final void Function(LatLng coordinates, String name) onLocationFound;
  final Future<void> Function() onShowFloatingCard;

  // These will hold the UI generated by your main.dart methods for now
  // final List<Widget> suggestedRoutesContent;

  const MainBottomSheet({
    super.key,
    required this.sheetController,
    required this.selectedIndex,
    required this.hasSuggestedRoutes,
    required this.onDrawMapElements,
    required this.onLocationFound,
    required this.onShowFloatingCard,
  });

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      controller: sheetController,
      initialChildSize: 0.0,
      minChildSize: 0.0,
      maxChildSize: 0.96,
      snap: true,
      snapSizes: const [0.26],
      builder: (BuildContext context, ScrollController scrollController) {
        return Container(
          decoration: const BoxDecoration(
            color: sheetBackgroundColor, 
            borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
            boxShadow: [BoxShadow(color: Colors.black26, blurRadius: 10)],
          ),
          child: ListView(
            controller: scrollController,
            padding: const EdgeInsets.all(16.0),
            children: [
              // 1. The Drag Handle
              Center(
                child: Container(
                  width: 40,
                  height: 5,
                  margin: const EdgeInsets.only(bottom: 20),
                  decoration: BoxDecoration(
                    color: Colors.black26,
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
              ),

              // 2. The Content Switcher
              if (selectedIndex == 0) ExploreSheetContent(onDrawMapElements: onDrawMapElements),
              if (selectedIndex == 1 && hasSuggestedRoutes) SuggestedRoutesContent(sheetController: sheetController, onDrawMapElements: onDrawMapElements, onShowFloatingCard: onShowFloatingCard),
              if (selectedIndex == 2) SearchSheetContent(onLocationFound: onLocationFound),
            ],
          ),
        );
      },
    );
  }
}

class ExploreSheetContent extends ConsumerStatefulWidget {
  final VoidCallback onDrawMapElements; // Remote control for main.dart's map!

  const ExploreSheetContent({
    super.key,
    required this.onDrawMapElements,
  });

  @override
  ConsumerState<ExploreSheetContent> createState() => _ExploreSheetContentState();
}

class _ExploreSheetContentState extends ConsumerState<ExploreSheetContent> {
  // THE FIX: These variables now live safely inside this specific tab!
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';
  bool _isSelectAllChecked = false;

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // 1. Read Riverpod directly! No need to pass it from main.dart anymore.
    final routeState = ref.watch(routeStateProvider);
    final allRoutes = routeState.allRoutes;

    final bool isSelectedRoute = allRoutes.any((route) => route.isVisible);

    // 2. Filter the routes based on the search box
    final filteredRoutes = allRoutes.where((route) {
      return route.name.toLowerCase().contains(_searchQuery.toLowerCase());
    }).toList();

    // 3. We wrap everything in a Column so it acts as a single block inside the ListView
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              'Kabalo Ba Ka?',
              style: TextStyle(
                fontSize: 32,
                fontWeight: FontWeight.w900,
                color: primaryColor,
                fontFamily: GoogleFonts.paytoneOne().fontFamily,
              ),
            ),
            GestureDetector(
              onTap: () async {
                await ref.read(routeStateProvider.notifier).toggleAllRoutes(false);
                setState(() {
                  _isSelectAllChecked = false;
                });
                widget.onDrawMapElements(); // Press the remote control!
              },
              child: AnimatedScale(
                duration: const Duration(milliseconds: 200),
                scale: isSelectedRoute ? 1.0 : 0.0,
                curve: Curves.ease,
                child: Container(
                  height: 35,
                  width: 85,
                  decoration: BoxDecoration(
                    color: isSelectedRoute ? deleteColor : sheetBackgroundColor,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: isSelectedRoute ? darkDeleteColor : sheetBackgroundColor,
                      width: 3,
                    ),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Container(
                        decoration: BoxDecoration(
                          color: isSelectedRoute ? fontColor : sheetBackgroundColor,
                          shape: BoxShape.circle,
                        ),
                        child: Icon(
                          Icons.close_rounded,
                          color: isSelectedRoute ? deleteColor : sheetBackgroundColor,
                          size: 15,
                        ),
                      ),
                      const SizedBox(width: 5),
                      Text(
                        "Clear",
                        style: TextStyle(
                          color: isSelectedRoute ? fontColor : sheetBackgroundColor,
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
        const SizedBox(height: 10),
        SizedBox(
          height: 40,
          child: AutoSizeText(
            'Discover the available jeepney routes in Davao City. Scroll or Search to find your specific route and Tap on the route.',
            style: const TextStyle(
              color: fontColor,
              fontSize: 16,
              height: 1.2,
            ),
            maxLines: 2,
            minFontSize: 10,
            overflow: TextOverflow.ellipsis,
          ),
        ),
        const SizedBox(height: 20),
        Container(
          margin: const EdgeInsets.symmetric(horizontal: 5),
          child: TextField(
            controller: _searchController,
            decoration: InputDecoration(
              hintText: 'Search for a route...',
              prefixIcon: const Icon(Icons.search),
              suffixIcon: _searchQuery.isNotEmpty
                  ? IconButton(
                      icon: const Icon(Icons.clear),
                      onPressed: () {
                        _searchController.clear();
                        setState(() => _searchQuery = '');
                      },
                    )
                  : null,
              filled: true,
              fillColor: fontColor,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(15),
                borderSide: BorderSide.none,
              ),
            ),
            onChanged: (value) {
              setState(() {
                _searchQuery = value;
              });
            },
          ),
        ),
        const SizedBox(height: 25),
        Card(
          margin: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 5),
          elevation: 10,
          color: cardColor,
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: _isSelectAllChecked ? primaryColor : Colors.transparent,
              width: 2,
            ),
            borderRadius: BorderRadius.circular(12),
          ),
          child: CheckboxListTile(
            title: const Text(
              "Select All Routes",
              style: TextStyle(
                fontWeight: FontWeight.bold,
                color: fontColor,
              ),
            ),
            value: _isSelectAllChecked,
            side: const BorderSide(color: Colors.transparent, width: 2),
            activeColor: Colors.transparent,
            checkColor: Colors.transparent,
            secondary: const Icon(
              Icons.select_all_rounded,
              color: fontColor,
              size: 30,
            ),
            onChanged: (bool? value) async {
              setState(() {
                _isSelectAllChecked = value ?? false;
              });

              if (value == true) {
                await ref.read(routeStateProvider.notifier).toggleAllRoutes(true);
                Fluttertoast.showToast(msg: 'Loading all routes on map', backgroundColor: cardColor);
              } else {
                await ref.read(routeStateProvider.notifier).toggleAllRoutes(false);
              }
              
              widget.onDrawMapElements(); // Press the remote control!
            },
          ),
        ),
        const SizedBox(height: 20),
        ...filteredRoutes.map((route) {
          return Card(
            margin: const EdgeInsets.symmetric(vertical: 4.0, horizontal: 5),
            clipBehavior: Clip.antiAlias,
            color: cardColor,
            elevation: 10,
            shape: RoundedRectangleBorder(
              side: BorderSide(
                color: route.isVisible ? primaryColor : Colors.transparent,
                width: 2,
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: CheckboxListTile(
              title: Text(
                route.name,
                style: const TextStyle(fontWeight: FontWeight.bold, color: fontColor),
              ),
              value: route.isVisible,
              side: const BorderSide(color: primaryColor, width: 2),
              activeColor: primaryColor,
              secondary: Container(
                width: 24,
                height: 24,
                decoration: BoxDecoration(
                  color: route.color,
                  borderRadius: BorderRadius.circular(30),
                  border: Border.all(color: Colors.black26),
                ),
              ),
              onChanged: (bool? value) async {
                await ref.read(routeStateProvider.notifier).handleRouteToggle(route);
                widget.onDrawMapElements(); // Press the remote control!
              },
            ),
          );
        }),
        const SizedBox(height: 80),
      ],
    );
  }
}

class SearchSheetContent extends ConsumerStatefulWidget {
  // The remote control! It passes the coordinates and name back to main.dart
  final void Function(LatLng coordinates, String name) onLocationFound;

  const SearchSheetContent({
    super.key,
    required this.onLocationFound,
  });

  @override
  ConsumerState<SearchSheetContent> createState() => _SearchSheetContentState();
}

class _SearchSheetContentState extends ConsumerState<SearchSheetContent> {
  final GeocodingService _geocodingService = GeocodingService();
  final HiveService _hiveService = HiveService();

  // We moved the History logic here because only the Search tab uses it!
  Future<void> _saveToHistory(String name, LatLng coords) async {
    final history = _hiveService.getHistory();
    history.sort((a, b) => a.id.compareTo(b.id));

    if (history.length >= 5) {
      await _hiveService.deleteLocation(history.first.id);
    }

    final newHistoryItem = FavoriteLocation(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      name: name,
      latitude: coords.latitude,
      longitude: coords.longitude,
      iconCodePoint: Icons.restore.codePoint,
      isFavorite: false,
    );

    await _hiveService.saveLocation(newHistoryItem);
    setState(() {}); // Refresh the history list on screen
  }

  @override
  Widget build(BuildContext context) {
    // Fetch live data from the local database
    final historyList = _hiveService.getHistory();
    historyList.sort((a, b) => b.id.compareTo(a.id));
    final favoritesList = _hiveService.getFavorites();

    // Wrap the original list of widgets in a Column
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          'Asa Ta?',
          style: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.w900,
            color: primaryColor,
            fontFamily: GoogleFonts.paytoneOne().fontFamily,
          ),
        ),
        const SizedBox(height: 10),
        SizedBox(
          height: 40,
          child: AutoSizeText(
            'Search a location by typing its name or pasting its coordinates from external maps using the Search Bar.',
            style: const TextStyle(color: fontColor, fontSize: 16, height: 1.2),
            maxLines: 2,
            minFontSize: 10,
            overflow: TextOverflow.ellipsis,
          ),
        ),
        const SizedBox(height: 20),

        // 1. THE DUAL-INPUT SEARCH BAR
        Container(
          margin: const EdgeInsets.symmetric(horizontal: 5),
          child: TextField(
            decoration: InputDecoration(
              hintText: 'Search here...',
              prefixIcon: const Icon(Icons.search),
              filled: true,
              fillColor: fontColor,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(15),
                borderSide: BorderSide.none,
              ),
            ),
            onSubmitted: (value) async {
              GeocodeResult? geocodeResult = await _geocodingService.searchLocation(value);

              if (geocodeResult != null) {
                // Tell main.dart to move the map!
                widget.onLocationFound(geocodeResult.coordinates, geocodeResult.name);
                await _saveToHistory(geocodeResult.name, geocodeResult.coordinates);
              }
            },
          ),
        ),
        const SizedBox(height: 24),

        // 2. FAVORITES SECTION
        const Text('Saved Places', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: fontColor)),
        const SizedBox(height: 10),
        if (favoritesList.isEmpty)
          const Text('No saved places yet. Long press a search result to save it here!', style: TextStyle(color: Colors.grey, fontStyle: FontStyle.italic))
        else
          SizedBox(
            height: 90,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: favoritesList.length,
              itemBuilder: (context, index) {
                final fav = favoritesList[index];
                return GestureDetector(
                  onTap: () {
                    // Tell main.dart to move the map!
                    widget.onLocationFound(LatLng(fav.latitude, fav.longitude), fav.name);
                  },
                  child: Container(
                    width: 100,
                    margin: const EdgeInsets.only(right: 12),
                    decoration: BoxDecoration(color: cardColor, borderRadius: BorderRadius.circular(15)),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(IconData(fav.iconCodePoint ?? 0, fontFamily: 'MaterialIcons'), color: primaryColor, size: 20),
                        const SizedBox(height: 8),
                        Text(fav.name, style: const TextStyle(color: fontColor, fontSize: 14, fontWeight: FontWeight.bold), textAlign: TextAlign.center, maxLines: 1, overflow: TextOverflow.ellipsis),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        const SizedBox(height: 24),

        // 3. RECENT SEARCHES SECTION
        const Text('Recent Searches', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: fontColor)),
        const SizedBox(height: 10),
        if (historyList.isEmpty)
          const Text('Your recent searches will appear here.', style: TextStyle(color: Colors.grey, fontStyle: FontStyle.italic))
        else
          ...historyList.map((historyItem) {
            return ListTile(
              contentPadding: EdgeInsets.zero,
              leading: CircleAvatar(
                backgroundColor: cardColor,
                child: Icon(IconData(historyItem.iconCodePoint ?? 0, fontFamily: 'MaterialIcons'), color: unselectedNavColor),
              ),
              title: Text(historyItem.name, style: const TextStyle(color: fontColor, fontWeight: FontWeight.bold)),
              subtitle: Text('${historyItem.latitude.toStringAsFixed(4)}, ${historyItem.longitude.toStringAsFixed(4)}', style: const TextStyle(color: Colors.grey, fontSize: 12)),
              trailing: IconButton(
                icon: const Icon(Icons.close, color: Colors.grey, size: 20),
                onPressed: () async {
                  await _hiveService.deleteLocation(historyItem.id);
                  setState(() {});
                },
              ),
              onTap: () {
                // Tell main.dart to move the map!
                widget.onLocationFound(LatLng(historyItem.latitude, historyItem.longitude), historyItem.name);
              },
            );
          }),
        const SizedBox(height: 80),
      ],
    );
  }
}

class SuggestedRoutesContent extends ConsumerStatefulWidget {
  final DraggableScrollableController sheetController;
  final VoidCallback onDrawMapElements;
  final Future<void> Function() onShowFloatingCard; // The remote control for the top card!

  const SuggestedRoutesContent({
    super.key,
    required this.sheetController,
    required this.onDrawMapElements,
    required this.onShowFloatingCard,
  });

  @override
  ConsumerState<SuggestedRoutesContent> createState() => _SuggestedRoutesContentState();
}

class _SuggestedRoutesContentState extends ConsumerState<SuggestedRoutesContent> {
  // We moved the Network Service here because only this tab uses it!
  final OsrmService _osrmService = OsrmService();

  @override
  Widget build(BuildContext context) {
    // 1. Read the pins from Riverpod
    final mapState = ref.watch(mapStateProvider);
    final startPin = mapState.startPin;
    final destinationPin = mapState.destinationPin;

    // 2. Read the routes from Riverpod
    final routeState = ref.watch(routeStateProvider);
    final allRoutes = routeState.allRoutes;
    final suggestedRoutes = routeState.suggestedRoutes;

    // 3. Sort the routes safely
    final List<RouteResult> sortedRoutes = List.from(suggestedRoutes);
    sortedRoutes.sort((a, b) {
      int fareComparison = a.estimatedFare.compareTo(b.estimatedFare);
      if (fareComparison != 0) return fareComparison;
      return a.totalEstimatedWalk.compareTo(b.totalEstimatedWalk);
    });

    // 4. Build the UI
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Text(
          'Suggested Routes',
          style: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: primaryColor,
            fontFamily: GoogleFonts.paytoneOne().fontFamily,
          ),
        ),
        const SizedBox(height: 10),
        const Text(
          'Pick the jeep you wish to ride and it will give you the walking distance, and estimated fare.',
          style: TextStyle(color: fontColor),
        ),
        ...sortedRoutes.asMap().entries.map((entry) {
          final int index = entry.key;
          final RouteResult result = entry.value;
          final bool isBestRoute = index == 0;

          return Card(
            margin: const EdgeInsets.symmetric(vertical: 15.0),
            color: btnColor,
            elevation: 10,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
            child: InkWell(
              borderRadius: BorderRadius.circular(20),
              onTap: () async {
                // 1. Tell main.dart to handle the sliding animation logic
                await widget.onShowFloatingCard();

                // 2. Update Riverpod and draw the map
                ref.read(routeStateProvider.notifier).setSelectedRoute(result);
                widget.onDrawMapElements();

                // 3. Slide the bottom sheet out of the way
                if (widget.sheetController.isAttached) {
                  widget.sheetController.animateTo(
                    0.26,
                    duration: const Duration(milliseconds: 300),
                    curve: Curves.easeInOut,
                  );
                }

                // 4. Fetch the walking paths from OSRM
                if (result.actualStartWalk == null && startPin != null && destinationPin != null) {
                  setState(() { result.isFetchingActualRoute = true; });

                  final routeData = allRoutes.firstWhere((r) => r.name == result.routeName);
                  final boardPoint = routeData.polylineData!.points[result.boardIndex];
                  final alightPoint = routeData.polylineData!.points[result.alightIndex];

                  final startLeg = await _osrmService.fetchWalkingRoute(startPin, boardPoint);
                  final endLeg = await _osrmService.fetchWalkingRoute(alightPoint, destinationPin);

                  if (startLeg != null && endLeg != null) {
                    setState(() {
                      result.actualWalkPathStart = startLeg['path'];
                      result.actualWalkPathEnd = endLeg['path'];
                      result.actualStartWalk = startLeg['distance'];
                      result.actualEndWalk = endLeg['distance'];
                    });
                    widget.onDrawMapElements();
                  }

                  setState(() { result.isFetchingActualRoute = false; });
                }
              },
              child: Container(
                height: 60,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: [
                    isBestRoute
                        ? const Icon(Icons.star_outline, size: 35, color: fontColor)
                        : Image.asset('assets/images/jeep_logo.png', width: 35, height: 35),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Flexible(
                            child: FittedBox(
                              fit: BoxFit.scaleDown,
                              alignment: Alignment.centerLeft,
                              child: Text(
                                result.routeName,
                                style: TextStyle(
                                  color: fontColor,
                                  fontSize: 25,
                                  fontFamily: GoogleFonts.paytoneOne().fontFamily,
                                  height: 1.0,
                                  shadows: [Shadow(offset: const Offset(1, 4), blurRadius: 7, color: Colors.black.withOpacity(0.5))],
                                ),
                              ),
                            ),
                          ),
                          if (isBestRoute)
                            const Padding(
                              padding: EdgeInsets.only(top: 2.0),
                              child: Text('RECOMMENDED', style: TextStyle(color: primaryColor, fontSize: 10, fontWeight: FontWeight.bold, height: 1.0)),
                            ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 16),
                    result.isFetchingActualRoute
                        ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2))
                        : const Icon(Icons.arrow_forward_ios, size: 16, color: fontColor),
                  ],
                ),
              ),
            ),
          );
        }),
        const SizedBox(height: 80),
      ],
    );
  }
}